### ISSUE TITLE
"Move Window to Desktop 9" is sending my windows to Desktop 10 instead

### ISSUE THREAD

**Issue by RobHoman** [folivoraAI/BetterTouchToolPlugins#3]
I think there could be a bug causing this in BetterTouchTool. It's been occurring somewhere in the realm of a month or two. I am running an external display that hosts spaces 1-10 and the MacBook display beneath it hosts spaces 11 & 12

My hotkeys for space management are
Shift+Ctrl+1 => "Move to Desktop 1"
Shift+Ctrl+2 => "Move to Desktop 2"
...
Shift+Ctrl+9 => "Move to Desktop 9"
Shift+Ctrl+0 => "Move to Desktop 10"

For some reason Shift+Ctrl+9 sends it to Desktop 10 instead of 9! All the others function as expected. I've tried deleting and recreating the rule. I've tried rebooting. I've tried deleting and recreating the spaces.

Mind taking a look if it could be a bug?

**Comment by RobHoman** [comment]
Oops... this isn't the main repo for BTT. My mistake. Looking elsewhere to log this.

**Comment by fifafu** [comment]
have a look at the BetterTouchTool community forums: https://community.folivora.ai
